name: Reusable workflow

on:
  workflow_call:
    inputs:
      user-name:
        required: true
        type: string
      address:
        required: true
        type: string
      age:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  shared-workflow-called:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Print variables
      run: |
        echo "User name: ${{ inputs.user-name }}"
        echo "Address: ${{ inputs.address }}"
        echo "Age: ${{ inputs.age }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
